# Docker compose file for NAP and meetbouten

web:
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - postgres:postgres
  volumes:
    - /usr/src/app/static
  env_file: .env
  command: /app/docker-entrypoint.sh
  environment:
    DISCOVERY_MODE: env
    SECRET_KEY: hoi

postgres:
  restart: always
  build: ./postgres
  volumes_from:
    - data
  ports:
    - "5433:5433"

data:
  restart: always
  build: ./postgres
  volumes:
    - /var/lib/postgresql
  command: "true"
