database:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  ports:
    - "5401:5432"
  environment:
    POSTGRES_PASSWORD: insecure

web:
  build: ./web
  ports:
    - "8100:8000"
  links:
    - database:database
  volumes:
    - $PWD/reports:/app/reports
  environment:
    SECRET_KEY: hoi
    DB_NAME: postgres
    DB_PASSWORD: insecure
