database:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  ports:
    - "5401:5432"
  environment:
    POSTGRES_DB: nap
    POSTGRES_USER: nap
    POSTGRES_PASSWORD: insecure

elasticsearch:
  image: admin.datapunt.amsterdam.nl:5000/atlas/elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9201:9200"
    - "9301:9300"

web:
  build: ./web
  ports:
    - "8100:8000"
  links:
    - database:database
    - elasticsearch:elastic
  volumes:
    - $PWD/reports:/app/reports
  environment:
    SECRET_KEY: hoi
    DB_NAME: nap
    DB_USER: nap
    DB_PASSWORD: insecure

