# Docker compose file for NAP and meetbouten

postgres:
  restart: always
  image: kartoza/postgis
  ports:
    - "5401:5432"

web:
  restart: always
  build: ./web
  ports:
    - "8100:8000"
  links:
    - postgres:postgres
  volumes:
    - /usr/src/app/static
  env_file: .env
  command: /app/atlas_nap_meetbouten/docker-entrypoint.sh
  environment:
    DISCOVERY_MODE: env
    SECRET_KEY: hoi
