version: '2.1'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: nap

  elasticsearch:
    image: build.datapunt.amsterdam.nl:5000/atlas/elasticsearch5
    volumes:
      - ./backups/elasticsearch:/tmp/backups
    user: root
    command: elasticsearch -Ehttp.host=0.0.0.0 -Etransport.host=127.0.0.1 -Epath.repo=/tmp


  importer:
    image: build.datapunt.amsterdam.nl:5000/datapunt/nap:${ENVIRONMENT}
    user: root
    links:
      - elasticsearch
      - database
    environment:
      DB_NAME: nap
      DB_USER: nap
      DB_PASSWORD: insecure
      BAG_OBJECTSTORE_PASSWORD:
      DATABASE_HOST_OVERRIDE: database
      DATABASE_PORT_OVERRIDE: 5432
      METADATA_URL: "${METADATA_URL}"
      DATAPUNT_API_URL: ${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
    command: >
      bash -c "/app/docker-wait.sh \
              && python objectstore/objectstore.py \
              && python manage.py migrate \
              && python manage.py run_import"

  db-backup:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    volumes:
      - ./backups:/tmp/backups
    command: >
      bash -c "echo database:5432:nap:nap:insecure > ~/.pgpass \
              && chmod 600 ~/.pgpass \
              && pg_dump --clean \
                          -Fc \
                          -t nap* \
                          -t meetbout* \
                          -t geo*  \
                          -T django*  \
                          -T auth*    \
                          -U nap \
                          -h database -p 5432 \
                          nap > /tmp/backups/database.dump"

  el-backup:
    image: build.datapunt.amsterdam.nl:5000/atlas/elasticsearch5
    volumes:
      - ./backups/elasticsearch:/tmp/backups
    user: root
    command: >
      bash -c "chmod -R 777 /tmp/backups \
              && curl -X PUT http://elasticsearch:9200/_snapshot/backup -d '{ \"type\": \"fs\", \"settings\": { \"location\": \"/tmp/backups\" }}' \
              && curl -X PUT http://elasticsearch:9200/_snapshot/backup/meetbouten?wait_for_completion=true -d '{ \"indices\": \"meetbouten\" }' \
              && chmod -R 777 /tmp/backups"
