# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_views', '0004_meetbouten_views'),
        ('geo_views', '0004_site_name'),
    ]

    operations = [
    ]
